### ISSUE TITLE
ihme <-  grab_ihme(): File does not exist

### ISSUE THREAD

**Issue by JLP04** [StateOfCalifornia/CalCAT#16] opened 2020-06-27 21:45 UTC
When the initial script to download data is run: it returns the following: 

> ihme <-  grab_ihme()
trying URL 'https://ihmecovid19storage.blob.core.windows.net/latest/ihme-covid19.zip'
Content type 'application/octet-stream' length 19866543 bytes (18.9 MB)
==================================================
downloaded 18.9 MB

Error in fread(file.path(temp2, paste0(folder, "/Hospitalization_all_locs.csv"))) : 
  File '/var/folders/kv/nt1xs5dd5637lbxxgg4z40n00000gn/T//RtmpXq2wsJ/file136c8464f30bd/2020_06_24.02/Hospitalization_all_locs.csv' does not exist or is non-readable. getwd()=='/Users/jasonpeskin/Desktop/CalCAT'

**Comment by joelrip** [comment] 2020-06-27 22:25
Duplicate of #11

**Comment by vargoCDPH** [comment] 2020-06-28 04:16
resolved via pull request

**Closed by vargoCDPH** 2020-06-28 04:16 UTC
